version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
    - netflix-study

  turbine-streamer:
    # build: ./turbine-streamer
    image: wesleyegberto/turbine-streamer
    ports:
    - 8989:8989
    - 8990:8990
    networks:
    - netflix-study
    depends_on:
    - eureka-server

  monitor-dashboard:
    # build: ./monitor-dashboard
    image: wesleyegberto/monitor-dashboard
    ports:
    - 7979:7979
    networks:
    - netflix-study

  eureka-server:
    # build: ./eureka-server
    image: wesleyegberto/eureka-server
    ports:
    - 8761:8761
    networks:
    - netflix-study

  zuul-server:
    # build: ./zuul-server
    image: wesleyegberto/zuul-server
    ports:
    - 8080:8080
    networks:
    - netflix-study
    depends_on:
    - eureka-server

  stock-service:
    # build: ./eureka-client-stock-service
    image: wesleyegberto/stock-service
    ports:
    - 8090:8090
    networks:
    - netflix-study
    depends_on:
    - eureka-server

  store-service:
    # build: ./eureka-client-store-service
    image: wesleyegberto/store-service
    ports:
    - 8095:8095
    networks:
    - netflix-study
    depends_on:
    - eureka-server

networks:
  netflix-study:
    driver: bridge
